require("dotenv").config();

module.exports = {
    PORT: process.env.PORT,

    AEROBOOK_USER_SERVICE:process.env.AEROBOOK_USER_SERVICE,
    AEROBOOK_FLIGHT_SERVICE:process.env.AEROBOOK_FLIGHT_SERVICE,
    AEROBOOK_BOOKING_SERVICE:process.env.AEROBOOK_BOOKING_SERVICE,
    AEROBOOK_PAYMENT_SERVICE:process.env.AEROBOOK_PAYMENT_SERVICE,
    AEROBOOK_NOTIFICATION_SERVICE:process.env.AEROBOOK_NOTIFICATION_SERVICE
};